default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: uno_development

test:
  <<: *default
  database: uno_test

production:
  <<: *default
  adapter: pg
  database: uno
  username: project-uno
  password: <%= ENV['PROJECT-UNO_DATABASE_PASSWORD'] %>
