development:
  adapter: mysql2
  database: uno_development
  pool: 20
  encoding: utf8
  username: root
  password: password
  host:  localhost

test:
  adapter: mysql2
  database: uno_test
  pool: 20
  encoding: utf8
  username: root
  password: password
  host:  localhost

production:
  adapter: mysql2
  database: uno
  pool: 20
  encoding: utf8
  username: root
  password: password
  host:  localhost