# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f63795f6d05293f7668a89d52ce1ceec48691c3453795e0e815f9c84fac97b2bb2a920c64ec545eadb75ad61d220e63ab1b75fd2d99fde930ad2ef07890f4f

test:
  secret_key_base: ac541e364001ddbd83222b130c2d8de74ee64fed40bb11ca40b52c763474ce668dc083be5a166fcdcca43ce48c4c4da44526ce82d43aa57eb6fd111015cb9695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
