# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22d21bcba7d875914cd5928eca4756896012ba5ebdd4acbaa7ec4b9ff4f2cec670c7ba38d21e1a5c113fbab7d83a9413a33cc7b0c57bacc819a154a795c1c345

test:
  secret_key_base: 15c0c39ac04bc6aa73e186063b2b11c1c55d7774d10c6e69cdaef17f0ed3cc0ec68a6fd5b81353f1a6de448cd428d371261eb06daf476d4616ac66bc8c177783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
