# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Card.delete_all
Card.create!([{ :id => 1, :value => 0, :color => "red", :url => "../public/images/cards/card_001.png" },
			  { :id => 2, :value => 1, :color => "red", :url => "../public/images/cards/card_002.png" },
			  { :id => 3, :value => 2, :color => "red", :url => "../public/images/cards/card_003.png" },
			  { :id => 4, :value => 3, :color => "red", :url => "../public/images/cards/card_004.png" },
			  { :id => 5,  :value => 4, :color => "red", :url => "../public/images/cards/card_005.png" },
			  { :id => 6,  :value => 5, :color => "red", :url => "../public/images/cards/card_006.png" }, 
			  { :id => 7,  :value => 6, :color => "red", :url => "../public/images/cards/card_007.png" },
			  { :id => 8,  :value => 7, :color => "red", :url => "../public/images/cards/card_008.png" },
			  { :id => 9,  :value => 8, :color => "red", :url => "../public/images/cards/card_009.png" }, 
			  { :id => 10, :value => 9, :color => "red", :url => "../public/images/cards/card_010.png" },
			  { :id => 11, :value => 10, :color => "red", :url => "../public/images/cards/card_011.png" },
			  { :id => 12, :value => 11, :color => "red", :url => "../public/images/cards/card_012.png" }, 
			  { :id => 13, :value => 12, :color => "red", :url => "../public/images/cards/card_013.png" },

			  { :id => 14, :value => 0, :color => "yellow", :url => "../public/images/cards/card_014.png" },
			  { :id => 15, :value => 1, :color => "yellow", :url => "../public/images/cards/card_015.png" },
			  { :id => 16, :value => 2, :color => "yellow", :url => "../public/images/cards/card_016.png" },
			  { :id => 17, :value => 3, :color => "yellow", :url => "../public/images/cards/card_017.png" },
			  { :id => 18, :value => 4, :color => "yellow", :url => "../public/images/cards/card_018.png" },
			  { :id => 19, :value => 5, :color => "yellow", :url => "../public/images/cards/card_019.png" }, 
			  { :id => 20, :value => 6, :color => "yellow", :url => "../public/images/cards/card_020.png" },
			  { :id => 21, :value => 7, :color => "yellow", :url => "../public/images/cards/card_021.png" },
			  { :id => 22, :value => 8, :color => "yellow", :url => "../public/images/cards/card_022.png" }, 
			  { :id => 23, :value => 9, :color => "yellow", :url => "../public/images/cards/card_023.png" },
			  { :id => 24, :value => 10, :color => "yellow", :url => "../public/images/cards/card_024.png" },
			  { :id => 25, :value => 11, :color => "yellow", :url => "../public/images/cards/card_025.png" }, 
			  { :id => 26, :value => 12, :color => "yellow", :url => "../public/images/cards/card_026.png" },

			  { :id => 27, :value => 0, :color => "green", :url => "../public/images/cards/card_027.png" },
			  { :id => 28, :value => 1, :color => "green", :url => "../public/images/cards/card_028.png" },
			  { :id => 29, :value => 2, :color => "green", :url => "../public/images/cards/card_029.png" },
			  { :id => 30, :value => 3, :color => "green", :url => "../public/images/cards/card_030.png" },
			  { :id => 31, :value => 4, :color => "green", :url => "../public/images/cards/card_031.png" },
			  { :id => 32, :value => 5, :color => "green", :url => "../public/images/cards/card_032.png" }, 
			  { :id => 33, :value => 6, :color => "green", :url => "../public/images/cards/card_033.png" },
			  { :id => 34, :value => 7, :color => "green", :url => "../public/images/cards/card_034.png" },
			  { :id => 35, :value => 8, :color => "green", :url => "../public/images/cards/card_035.png" }, 
			  { :id => 36, :value => 9, :color => "green", :url => "../public/images/cards/card_036.png" },
			  { :id => 37, :value => 10, :color => "green", :url => "../public/images/cards/card_037.png" },
			  { :id => 38, :value => 11, :color => "green", :url => "../public/images/cards/card_038.png" }, 
			  { :id => 39, :value => 12, :color => "green", :url => "../public/images/cards/card_039.png" },

			  { :id => 40, :value => 0, :color => "blue", :url => "../public/images/cards/card_040.png" },
			  { :id => 41, :value => 1, :color => "blue", :url => "../public/images/cards/card_041.png" },
			  { :id => 42, :value => 2, :color => "blue", :url => "../public/images/cards/card_042.png" },
			  { :id => 43, :value => 3, :color => "blue", :url => "../public/images/cards/card_043.png" },
			  { :id => 44, :value => 4, :color => "blue", :url => "../public/images/cards/card_044.png" },
			  { :id => 45, :value => 5, :color => "blue", :url => "../public/images/cards/card_045.png" }, 
			  { :id => 46, :value => 6, :color => "blue", :url => "../public/images/cards/card_046.png" },
			  { :id => 47, :value => 7, :color => "blue", :url => "../public/images/cards/card_047.png" },
			  { :id => 48, :value => 8, :color => "blue", :url => "../public/images/cards/card_048.png" }, 
			  { :id => 49, :value => 9, :color => "blue", :url => "../public/images/cards/card_049.png" },
			  { :id => 50, :value => 10, :color => "blue", :url => "../public/images/cards/card_050.png" },
			  { :id => 51, :value => 11, :color => "blue", :url => "../public/images/cards/card_051.png" }, 
			  { :id => 52, :value => 12, :color => "blue", :url => "../public/images/cards/card_052.png" },

			  { :id => 53, :value => 1, :color => "red", :url => "../public/images/cards/card_053.png" },
			  { :id => 54, :value => 2, :color => "red", :url => "../public/images/cards/card_054.png" },
			  { :id => 55, :value => 3, :color => "red", :url => "../public/images/cards/card_055.png" },
			  { :id => 56, :value => 4, :color => "red", :url => "../public/images/cards/card_056.png" },
			  { :id => 57, :value => 5, :color => "red", :url => "../public/images/cards/card_057.png" }, 
			  { :id => 58, :value => 6, :color => "red", :url => "../public/images/cards/card_058.png" },
			  { :id => 59, :value => 7, :color => "red", :url => "../public/images/cards/card_059.png" },
			  { :id => 60, :value => 8, :color => "red", :url => "../public/images/cards/card_060.png" }, 
			  { :id => 61, :value => 9, :color => "red", :url => "../public/images/cards/card_061.png" },
			  { :id => 62, :value => 10, :color => "red", :url => "../public/images/cards/card_062.png" },
			  { :id => 63, :value => 11, :color => "red", :url => "../public/images/cards/card_063.png" }, 
			  { :id => 64, :value => 12, :color => "red", :url => "../public/images/cards/card_064.png" },

			  { :id => 65, :value => 1, :color => "yellow", :url => "../public/images/cards/card_065.png" },
			  { :id => 66, :value => 2, :color => "yellow", :url => "../public/images/cards/card_066.png" },
			  { :id => 67, :value => 3, :color => "yellow", :url => "../public/images/cards/card_067.png" },
			  { :id => 68, :value => 4, :color => "yellow", :url => "../public/images/cards/card_068.png" },
			  { :id => 69, :value => 5, :color => "yellow", :url => "../public/images/cards/card_069.png" }, 
			  { :id => 70, :value => 6, :color => "yellow", :url => "../public/images/cards/card_070.png" },
			  { :id => 71, :value => 7, :color => "yellow", :url => "../public/images/cards/card_071.png" },
			  { :id => 72, :value => 8, :color => "yellow", :url => "../public/images/cards/card_072.png" }, 
			  { :id => 73, :value => 9, :color => "yellow", :url => "../public/images/cards/card_073.png" },
			  { :id => 74, :value => 10, :color => "yellow", :url => "../public/images/cards/card_074.png" },
			  { :id => 75, :value => 11, :color => "yellow", :url => "../public/images/cards/card_075.png" }, 
			  { :id => 76, :value => 12, :color => "yellow", :url => "../public/images/cards/card_076.png" },

			  { :id => 77, :value => 1, :color => "green", :url => "../public/images/cards/card_077.png" },
			  { :id => 78, :value => 2, :color => "green", :url => "../public/images/cards/card_078.png" },
			  { :id => 79, :value => 3, :color => "green", :url => "../public/images/cards/card_079.png" },
			  { :id => 80, :value => 4, :color => "green", :url => "../public/images/cards/card_080.png" },
			  { :id => 81, :value => 5, :color => "green", :url => "../public/images/cards/card_081.png" }, 
			  { :id => 82, :value => 6, :color => "green", :url => "../public/images/cards/card_082.png" },
			  { :id => 83, :value => 7, :color => "green", :url => "../public/images/cards/card_083.png" },
			  { :id => 84, :value => 8, :color => "green", :url => "../public/images/cards/card_084.png" }, 
			  { :id => 85, :value => 9, :color => "green", :url => "../public/images/cards/card_085.png" },
			  { :id => 86, :value => 10, :color => "green", :url => "../public/images/cards/card_086.png" },
			  { :id => 87, :value => 11, :color => "green", :url => "../public/images/cards/card_087.png" }, 
			  { :id => 88, :value => 12, :color => "green", :url => "../public/images/cards/card_088.png" },
			  
			  { :id => 89, :value => 1, :color => "blue", :url => "../public/images/cards/card_089.png" },
			  { :id => 90, :value => 2, :color => "blue", :url => "../public/images/cards/card_090.png" },
			  { :id => 91, :value => 3, :color => "blue", :url => "../public/images/cards/card_091.png" },
			  { :id => 92, :value => 4, :color => "blue", :url => "../public/images/cards/card_092.png" },
			  { :id => 93, :value => 5, :color => "blue", :url => "../public/images/cards/card_093.png" }, 
			  { :id => 94, :value => 6, :color => "blue", :url => "../public/images/cards/card_094.png" },
			  { :id => 95, :value => 7, :color => "blue", :url => "../public/images/cards/card_095.png" },
			  { :id => 96, :value => 8, :color => "blue", :url => "../public/images/cards/card_096.png" }, 
			  { :id => 97, :value => 9, :color => "blue", :url => "../public/images/cards/card_097.png" },
			  { :id => 98, :value => 10, :color => "blue", :url => "../public/images/cards/card_098.png" },
			  { :id => 99, :value => 11, :color => "blue", :url => "../public/images/cards/card_099.png" }, 
			  { :id => 100, :value => 12, :color => "blue", :url => "../public/images/cards/card_100.png" },


			  { :id => 101, :value => 0, :color => "black", :url => "../public/images/cards/card_101.png" },
			  { :id => 102, :value => 0, :color => "black", :url => "../public/images/cards/card_102.png" },
			  { :id => 103, :value => 0, :color => "black", :url => "../public/images/cards/card_103.png" },
			  { :id => 104, :value => 0, :color => "black", :url => "../public/images/cards/card_104.png" },
			  { :id => 105, :value => 1, :color => "black", :url => "../public/images/cards/card_105.png" },
			  { :id => 106, :value => 1, :color => "black", :url => "../public/images/cards/card_106.png" },
			  { :id => 107, :value => 1, :color => "black", :url => "../public/images/cards/card_107.png" },
			  { :id => 108, :value => 1, :color => "black", :url => "../public/images/cards/card_108.png" },]) 