# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Card.delete_all
Card.create!([{ :id => 1, :value => 0, :color => "red" },
			  { :id => 2, :value => 1, :color => "red" },
			  { :id => 3, :value => 2, :color => "red" },
			  { :id => 4, :value => 3, :color => "red" },
			  { :id => 5,  :value => 4, :color => "red" },
			  { :id => 6,  :value => 5, :color => "red" }, 
			  { :id => 7,  :value => 6, :color => "red" },
			  { :id => 8,  :value => 7, :color => "red" },
			  { :id => 9,  :value => 8, :color => "red" }, 
			  { :id => 10, :value => 9, :color => "red" },
			  { :id => 11, :value => 10, :color => "red" },
			  { :id => 12, :value => 11, :color => "red" }, 
			  { :id => 13, :value => 12, :color => "red" },
			  { :id => 14, :value => 0, :color => "black" },

			  { :id => 15, :value => 0, :color => "yellow" },
			  { :id => 16, :value => 1, :color => "yellow" },
			  { :id => 17, :value => 2, :color => "yellow" },
			  { :id => 18, :value => 3, :color => "yellow" },
			  { :id => 19, :value => 4, :color => "yellow" },
			  { :id => 20, :value => 5, :color => "yellow" }, 
			  { :id => 21, :value => 6, :color => "yellow" },
			  { :id => 22, :value => 7, :color => "yellow" },
			  { :id => 23, :value => 8, :color => "yellow" }, 
			  { :id => 24, :value => 9, :color => "yellow" },
			  { :id => 25, :value => 10, :color => "yellow" },
			  { :id => 26, :value => 11, :color => "yellow" }, 
			  { :id => 27, :value => 12, :color => "yellow" },
			  { :id => 28, :value => 0, :color => "black" },

			  { :id => 29, :value => 0, :color => "green" },
			  { :id => 30, :value => 1, :color => "green" },
			  { :id => 31, :value => 2, :color => "green" },
			  { :id => 32, :value => 3, :color => "green" },
			  { :id => 33, :value => 4, :color => "green" },
			  { :id => 34, :value => 5, :color => "green" }, 
			  { :id => 35, :value => 6, :color => "green" },
			  { :id => 36, :value => 7, :color => "green" },
			  { :id => 37, :value => 8, :color => "green" }, 
			  { :id => 38, :value => 9, :color => "green" },
			  { :id => 39, :value => 10, :color => "green" },
			  { :id => 40, :value => 11, :color => "green" }, 
			  { :id => 41, :value => 12, :color => "green" },
			  { :id => 42, :value => 0, :color => "black" },

			  { :id => 43, :value => 0, :color => "blue" },
			  { :id => 44, :value => 1, :color => "blue" },
			  { :id => 45, :value => 2, :color => "blue" },
			  { :id => 46, :value => 3, :color => "blue" },
			  { :id => 47, :value => 4, :color => "blue" },
			  { :id => 48, :value => 5, :color => "blue" }, 
			  { :id => 49, :value => 6, :color => "blue" },
			  { :id => 50, :value => 7, :color => "blue" },
			  { :id => 51, :value => 8, :color => "blue" }, 
			  { :id => 52, :value => 9, :color => "blue" },
			  { :id => 53, :value => 10, :color => "blue" },
			  { :id => 54, :value => 11, :color => "blue" }, 
			  { :id => 55, :value => 12, :color => "blue" },
			  { :id => 56, :value => 0, :color => "black" },

			  { :id => 57, :value => 1, :color => "red" },
			  { :id => 58, :value => 2, :color => "red" },
			  { :id => 59, :value => 3, :color => "red" },
			  { :id => 60, :value => 4, :color => "red" },
			  { :id => 61, :value => 5, :color => "red" }, 
			  { :id => 62, :value => 6, :color => "red" },
			  { :id => 63, :value => 7, :color => "red" },
			  { :id => 64, :value => 8, :color => "red" }, 
			  { :id => 65, :value => 9, :color => "red" },
			  { :id => 66, :value => 10, :color => "red" },
			  { :id => 67, :value => 11, :color => "red" }, 
			  { :id => 68, :value => 12, :color => "red" },
			  { :id => 69, :value => 1, :color => "black" },

			  { :id => 70, :value => 1, :color => "yellow" },
			  { :id => 71, :value => 2, :color => "yellow" },
			  { :id => 72, :value => 3, :color => "yellow" },
			  { :id => 73, :value => 4, :color => "yellow" },
			  { :id => 74, :value => 5, :color => "yellow" }, 
			  { :id => 75, :value => 6, :color => "yellow" },
			  { :id => 76, :value => 7, :color => "yellow" },
			  { :id => 77, :value => 8, :color => "yellow" }, 
			  { :id => 78, :value => 9, :color => "yellow" },
			  { :id => 79, :value => 10, :color => "yellow" },
			  { :id => 80, :value => 11, :color => "yellow" }, 
			  { :id => 81, :value => 12, :color => "yellow" },
			  { :id => 82, :value => 1, :color => "black" },

			  { :id => 83, :value => 1, :color => "green" },
			  { :id => 84, :value => 2, :color => "green" },
			  { :id => 85, :value => 3, :color => "green" },
			  { :id => 86, :value => 4, :color => "green" },
			  { :id => 87, :value => 5, :color => "green" }, 
			  { :id => 88, :value => 6, :color => "green" },
			  { :id => 89, :value => 7, :color => "green" },
			  { :id => 90, :value => 8, :color => "green" }, 
			  { :id => 91, :value => 9, :color => "green" },
			  { :id => 92, :value => 10, :color => "green" },
			  { :id => 93, :value => 11, :color => "green" }, 
			  { :id => 94, :value => 12, :color => "green" },
			  { :id => 95, :value => 1, :color => "black" },
			  
			  { :id => 96, :value => 1, :color => "blue" },
			  { :id => 97, :value => 2, :color => "blue" },
			  { :id => 98, :value => 3, :color => "blue" },
			  { :id => 99, :value => 4, :color => "blue" },
			  { :id => 100, :value => 5, :color => "blue" }, 
			  { :id => 101, :value => 6, :color => "blue" },
			  { :id => 102, :value => 7, :color => "blue" },
			  { :id => 103, :value => 8, :color => "blue" }, 
			  { :id => 104, :value => 9, :color => "blue" },
			  { :id => 105, :value => 10, :color => "blue" },
			  { :id => 106, :value => 11, :color => "blue" }, 
			  { :id => 107, :value => 12, :color => "blue" },
			  { :id => 108, :value => 1, :color => "black" }]) 